[package]
name = "url-shortener"
version = "0.1.0"
authors = ["Oran C <Oranbusiness@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
